package com.example.user.bookstore.Database;

/**
 * Created by user on 18/11/16.
 */

public enum Action {
    LOGIN,
    REGISTER,
    GETBOOKS,
    GETINFO,
    GIVENFEEDBACK,
    INPUTFEEDBACK,
    GETAVERAGERATE,
    GETFEEDBACK,
    GETBOOKSFILTERED,
    PLACEORDER,
    DELETEUSEFULNESS,
    UPDATEUSEFULNESS,
    INSERTUSEFULNESS,
    GETRECOMMENDATION,
    GETPROFILE,
    UPDATEPROFILE

}
